# Generated by Django 5.2.10 on 2026-02-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archives', '0004_category_cart_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
