# Generated by Django 5.2.10 on 2026-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archives', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
