# Generated by Django 5.2.10 on 2026-02-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archives', '0006_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
