# Generated by Django 5.2.10 on 2026-04-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archives', '0011_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
    ]
