# Generated by Django 5.2.10 on 2026-04-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archives', '0012_remove_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
